### PR TITLE
[pypi] add guidelines for configuring multiple index urls

### PR DESCRIPTION
**Pull request by wordlesswind**
The `--extra-index-url` option allows the user to configure multiple index urls, thus balancing the load.

### CODE REVIEW

**Comment by ZenithalHourlyRate** [comment]
Then the default index url would be <https://pypi.org/simple> and the user experience could be bad.

You may add a section that shows TUNA can be used alongside other mirror sites with `extra-index-url` with some mirror configured as the primary index. It would be appreciated if an example of multiple `extra-index-url` is added.

You may guide users to https://mirrors.cernet.edu.cn/list/pypi for available pypi mirrors.

**Comment by wordlesswind** [comment]
> You may guide users to https://mirrors.cernet.edu.cn/list/pypi for available pypi mirrors.

modified

**Comment by ZenithalHourlyRate** [comment]
> Then the default index url would be https://pypi.org/simple and the user experience could be bad.

I made some surveys. It seems that `index-url` and `extra-index-url` are treated equally. See https://github.com/pypa/pip/issues/11458 for the most relevant setting.

An experiment shows that only configuring extra-index-url is not enough. However, users may still download packages from pypi.org and get a bad experience. In the following example, `numpy` is downloaded from `files.pythonhosted.org` instead of TUNA.

```sh
$ pip3 config set global.extra-index-url "https://pypi.tuna.tsinghua.edu.cn/simple"
Writing to /root/.config/pip/pip.conf
$ pip3 install numpy
Looking in indexes: https://pypi.org/simple, https://pypi.tuna.tsinghua.edu.cn/simple
Collecting numpy
  Downloading numpy-1.23.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.1 MB)
     |████████████████████████████████| 17.1 MB 3.3 MB/s 
Installing collected packages: numpy
Successfully installed numpy-1.23.4
```

The guide should say that index-url should be some mirror and if you want load balancing, you can put them in extra-index-url, as I said before

> You may add a section that shows TUNA can be used alongside other mirror sites with extra-index-url **with some mirror configured as the primary index**.

**Comment by wordlesswind** [comment]
> The guide should say that index-url should be some mirror and if you want load balancing, you can put them in extra-index-url, as I said before
> 
> > You may add a section that shows TUNA can be used alongside other mirror sites with extra-index-url **with some mirror configured as the primary index**.

so I've modified it. you don't seem to have checked my changes.

and I would say that you downloaded `numpy` from `files.pythonhosted.org` maybe because you configured a proxy, I don't think the "3.3 MB/s" download speed is a bad experience.

**Comment by ZenithalHourlyRate** [comment]
> 如果您想配置多个镜像源平衡负载，可进行如下配置：

I just want a simple change in the description.

> 如果您想配置多个镜像源平衡负载，可在已经替换 index-url 的情况下通过以下方式继续增加源站：

**Comment by wordlesswind** [comment]
> > 如果您想配置多个镜像源平衡负载，可进行如下配置：
> 
> I just want a simple change in the description.
> 
> > 如果您想配置多个镜像源平衡负载，可在已经替换 index-url 的情况下通过以下方式继续增加源站：

ok, I have modified it.

**Pull request merged**
