### PR TITLE
Add deepmodeling to default conda channels

### PR DESCRIPTION
**Pull request by caic99**
[DeepModeling](deepmodeling.com) is a popular AI-assisted scientific computing open source community. Currently, most of its softwares are hosted in the `deepmodeling` conda channel.

### CODE REVIEW

**Comment by caic99** [comment]
Any updates? 👀

**Comment by ZenithalHourlyRate** [comment]
https://github.com/tuna/issues/issues/1232#issuecomment-1515067378

**Comment by caic99** [comment]
> [tuna/issues#1232 (comment)](https://github.com/tuna/issues/issues/1232#issuecomment-1515067378)

Hi @ZenithalHourlyRate ,
您关心的是合规性问题吗？我可以联系deepmodeling社区的人员给出许可。

**Comment by ZenithalHourlyRate** [comment]
主要 anaconda 目前总大小较大，且增长无限制

**Comment by ZenithalHourlyRate** [comment]
> 您关心的是合规性问题吗？我可以联系deepmodeling社区的人员给出许可。

后来意识到这并不是镜像请求。

**Pull request merged**
