### PR TITLE
添加 Eclipse IDE 直接下载链接配置

### PR DESCRIPTION
**Pull request by smnet1999**

### CODE REVIEW

**Comment by jiegec** [comment]
LGTM, thanks! Let's see whether it works.

**Comment by smnet1999** [comment]
> LGTM, thanks! Let's see whether it works.

It seems not work,when I click the "获取下载链接" button,nothing displayed.
Sorry!

**Comment by jiegec** [comment]
Oh, that's because we have not deployed it. Please be patient.

**Comment by jiegec** [comment]
We are doing some tests on it.

**Comment by z4yx** [comment]
It works now.

**Comment by Harry-Chen** [comment]
"Fix my error" would not be a good commit message. Consider squashing your commits or using a more descriptive message next time.

**Pull request merged**
